export const suggestions = [
  {
    value: 'realCosts',
    label: 'Real costs',
  },
  {
    value: 'hotelRooms',
    label: 'Hotel rooms',
  },
  {
    value: 'offlineDeadHeads',
    label: 'Offline deadheads',
  },
  {
    value: 'aircraftChanges',
    label: 'Aircraft changes',
  },
  {
    value: 'splitDuties',
    label: 'Split duties',
  },
  {
    value: 'blockPerDutyDay',
    label: 'Block per duty day',
  },
  {
    value: 'blockPerDutyPeriod',
    label: 'Block per duty period',
  },
  {
    value: 'percent1DayPairings',
    label: 'Percent 1-day pairings',
  },
  {
    value: 'percent2DayPairings',
    label: 'Percent 2-day pairings',
  },
  {
    value: 'percent3DayPairing',
    label: 'Percent 3+ day pairings',
  },
];

export const Data = [
  {
    id: 1,
    data: {
      realCosts: {
        total: '3 617 880',
        cdg: '1 607 843',
        nce: '677 243',
        lys: '667 243',
      },
      hotelRooms: {
        total: 502,
        cdg: 243,
        nce: 211,
        lys: 91,
      },
      offlineDeadHeads: {
        total: 553,
        cdg: 31,
        nce: 153,
        lys: 57,
      },
      aircraftChanges: {
        total: 22,
        cdg: 12,
        nce: 6,
        lys: 4,
      },
      splitDuties: {
        total: 41,
        cdg: 18,
        nce: 7,
        lys: 16,
      },
      blockPerDutyDay: {
        total: '4h49',
        cdg: '4h53',
        nce: '4h40',
        lys: '4h50',
      },
      blockPerDutyPeriod: {
        total: '4h20',
        cdg: '4h33',
        nce: '5h10',
        lys: '4h58',
      },
      percent1DayPairings: {
        total: '58%',
        cdg: '60%',
        nce: '54%',
        lys: '49%',
      },
      percent2DayPairings: {
        total: '60%',
        cdg: '30%',
        nce: '20%',
        lys: '10%',
      },
      percent3DayPairing: {
        total: '58%',
        cdg: '15%',
        nce: '50%',
        lys: '9%',
      },
    },
  },
  {
    id: 2,
    data: {
      realCosts: {
        total: '3 384 775',
        cdg: '1 765 224',
        nce: '942 308',
        lys: '677 243',
      },
      hotelRooms: {
        total: 709,
        cdg: 347,
        nce: 264,
        lys: 98,
      },
      offlineDeadHeads: {
        total: 191,
        cdg: 64,
        nce: 89,
        lys: 38,
      },
      aircraftChanges: {
        total: 46,
        cdg: 14,
        nce: 7,
        lys: 25,
      },
      splitDuties: {
        total: 30,
        cdg: 5,
        nce: 15,
        lys: 10,
      },
      blockPerDutyDay: {
        total: '4h55',
        cdg: '4h42',
        nce: '5h01',
        lys: '4h53',
      },
      blockPerDutyPeriod: {
        total: '5h20',
        cdg: '5h33',
        nce: '4h10',
        lys: '4h58',
      },
      percent1DayPairings: {
        total: '62%',
        cdg: '58%',
        nce: '67%',
        lys: '60%',
      },
      percent2DayPairings: {
        total: '40%',
        cdg: '20%',
        nce: '15%',
        lys: '5%',
      },
      percent3DayPairing: {
        total: '80%',
        cdg: '15%',
        nce: '50%',
        lys: '15%',
      },
    },
  },
  {
    id: 3,
    data: {
      realCosts: {
        total: '2 265 108',
        cdg: '1 000 099',
        nce: '862 974',
        lys: '321 007',
      },
      hotelRooms: {
        total: 201,
        cdg: 143,
        nce: 44,
        lys: 18,
      },
      offlineDeadHeads: {
        total: 154,
        cdg: 92,
        nce: 30,
        lys: 32,
      },
      aircraftChanges: {
        total: 6,
        cdg: 2,
        nce: 1,
        lys: 3,
      },
      splitDuties: {
        total: 35,
        cdg: 20,
        nce: 5,
        lys: 10,
      },
      blockPerDutyDay: {
        total: '4h31',
        cdg: '4h44',
        nce: '4h22',
        lys: '4h33',
      },
      blockPerDutyPeriod: {
        total: '3h20',
        cdg: '3h28',
        nce: '5h15',
        lys: '4h40',
      },
      percent1DayPairings: {
        total: '27%',
        cdg: '18%',
        nce: '29%',
        lys: '26%',
      },
      percent2DayPairings: {
        total: '40%',
        cdg: '30%',
        nce: '2%',
        lys: '8%',
      },
      percent3DayPairing: {
        total: '29%',
        cdg: '33%',
        nce: '42%',
        lys: '54%',
      },
    },
  },
  {
    id: 4,
    data: {
      realCosts: {
        total: '2 102 333',
        cdg: '942 308',
        nce: '770 118',
        lys: '942 308',
      },
      hotelRooms: {
        total: 189,
        cdg: 92,
        nce: 54,
        lys: 51,
      },
      offlineDeadHeads: {
        total: 72,
        cdg: 21,
        nce: 22,
        lys: 19,
      },
      aircraftChanges: {
        total: 7,
        cdg: 2,
        nce: 2,
        lys: 3,
      },
      splitDuties: {
        total: 28,
        cdg: 18,
        nce: 5,
        lys: 5,
      },
      blockPerDutyDay: {
        total: '4h22',
        cdg: '4h10',
        nce: '4h28',
        lys: '4h13',
      },
      blockPerDutyPeriod: {
        total: '1h20',
        cdg: '2h33',
        nce: '3h10',
        lys: '4h58',
      },
      percent1DayPairings: {
        total: '31%',
        cdg: '44%',
        nce: '17%',
        lys: '21%',
      },
      percent2DayPairings: {
        total: '38%',
        cdg: '28%',
        nce: '19%',
        lys: '45%',
      },
      percent3DayPairing: {
        total: '60%',
        cdg: '50%',
        nce: '40%',
        lys: '30%',
      },
    },
  },
  {
    id: 5,
    data: {
      realCosts: {
        total: '3 617 880',
        cdg: '1 607 843',
        nce: '677 243',
        lys: '677 243',
      },
      hotelRooms: {
        total: 502,
        cdg: 243,
        nce: 211,
        lys: 91,
      },
      offlineDeadHeads: {
        total: 553,
        cdg: 31,
        nce: 153,
        lys: 57,
      },
      aircraftChanges: {
        total: 22,
        cdg: 12,
        nce: 6,
        lys: 4,
      },
      splitDuties: {
        total: 35,
        cdg: 15,
        nce: 19,
        lys: 1,
      },
      blockPerDutyDay: {
        total: '4h49',
        cdg: '4h53',
        nce: '4h40',
        lys: '4h50',
      },
      blockPerDutyPeriod: {
        total: '4h20',
        cdg: '4h33',
        nce: '5h10',
        lys: '4h58',
      },
      percent1DayPairings: {
        total: '58%',
        cdg: '60%',
        nce: '54%',
        lys: '49%',
      },
      percent2DayPairings: {
        total: '70%',
        cdg: '60%',
        nce: '50%',
        lys: '40%',
      },
      percent3DayPairing: {
        total: '20%',
        cdg: '30%',
        nce: '40%',
        lys: '50%',
      },
    },
  },
  {
    id: 6,
    data: {
      realCosts: {
        total: '3 384 775',
        cdg: '1 765 224',
        nce: '942 308',
        lys: '677 243',
      },
      hotelRooms: {
        total: 709,
        cdg: 347,
        nce: 264,
        lys: 98,
      },
      offlineDeadHeads: {
        total: 191,
        cdg: 64,
        nce: 89,
        lys: 38,
      },
      aircraftChanges: {
        total: 46,
        cdg: 14,
        nce: 7,
        lys: 25,
      },
      splitDuties: {
        total: 120,
        cdg: 20,
        nce: 9,
        lys: 91,
      },
      blockPerDutyDay: {
        total: '4h55',
        cdg: '4h42',
        nce: '5h01',
        lys: '4h53',
      },
      blockPerDutyPeriod: {
        total: '1h20',
        cdg: '2h33',
        nce: '3h10',
        lys: '7h58',
      },
      percent1DayPairings: {
        total: '62%',
        cdg: '58%',
        nce: '67%',
        lys: '60%',
      },
      percent2DayPairings: {
        total: '18%',
        cdg: '28%',
        nce: '38%',
        lys: '48%',
      },
      percent3DayPairing: {
        total: '58%',
        cdg: '68%',
        nce: '78%',
        lys: '88%',
      },
    },
  },
  {
    id: 7,
    data: {
      realCosts: {
        total: '2 102 333',
        cdg: '942 308',
        nce: '770 118',
        lys: '942 308',
      },
      hotelRooms: {
        total: 189,
        cdg: 92,
        nce: 54,
        lys: 51,
      },
      offlineDeadHeads: {
        total: 72,
        cdg: 21,
        nce: 22,
        lys: 19,
      },
      aircraftChanges: {
        total: 7,
        cdg: 2,
        nce: 2,
        lys: 3,
      },
      splitDuties: {
        total: 51,
        cdg: 23,
        nce: 9,
        lys: 18,
      },
      blockPerDutyDay: {
        total: '4h22',
        cdg: '4h10',
        nce: '4h28',
        lys: '4h13',
      },
      blockPerDutyPeriod: {
        total: '6h40',
        cdg: '5h53',
        nce: '4h50',
        lys: '3h50',
      },
      percent1DayPairings: {
        total: '31%',
        cdg: '44%',
        nce: '17%',
        lys: '21%',
      },
      percent2DayPairings: {
        total: '65%',
        cdg: '35%',
        nce: '25%',
        lys: '15%',
      },
      percent3DayPairing: {
        total: '18%',
        cdg: '19%',
        nce: '20%',
        lys: '21%',
      },
    },
  },
  {
    id: 8,
    data: {
      realCosts: {
        total: '2 102 333',
        cdg: '942 308',
        nce: '770 118',
        lys: '942 308',
      },
      hotelRooms: {
        total: 189,
        cdg: 92,
        nce: 54,
        lys: 51,
      },
      offlineDeadHeads: {
        total: 72,
        cdg: 21,
        nce: 22,
        lys: 19,
      },
      aircraftChanges: {
        total: 7,
        cdg: 2,
        nce: 2,
        lys: 3,
      },
      splitDuties: {
        total: 182,
        cdg: 71,
        nce: 9,
        lys: 102,
      },
      blockPerDutyDay: {
        total: '4h22',
        cdg: '4h10',
        nce: '4h28',
        lys: '4h13',
      },
      blockPerDutyPeriod: {
        total: '4h50',
        cdg: '4h35',
        nce: '5h15',
        lys: '4h55',
      },
      percent1DayPairings: {
        total: '31%',
        cdg: '44%',
        nce: '17%',
        lys: '21%',
      },
      percent2DayPairings: {
        total: '10%',
        cdg: '10%',
        nce: '10%',
        lys: '10%',
      },
      percent3DayPairing: {
        total: '28%',
        cdg: '28%',
        nce: '28%',
        lys: '28%',
      },
    },
  },
  {
    id: 9,
    data: {
      realCosts: {
        total: '3 617 880',
        cdg: '1 607 843',
        nce: '677 243',
        lys: '677 243',
      },
      hotelRooms: {
        total: 502,
        cdg: 243,
        nce: 211,
        lys: 91,
      },
      offlineDeadHeads: {
        total: 553,
        cdg: 31,
        nce: 153,
        lys: 57,
      },
      aircraftChanges: {
        total: 22,
        cdg: 12,
        nce: 6,
        lys: 4,
      },
      splitDuties: {
        total: 77,
        cdg: 25,
        nce: 35,
        lys: 17,
      },
      blockPerDutyDay: {
        total: '4h49',
        cdg: '4h53',
        nce: '4h40',
        lys: '4h50',
      },
      blockPerDutyPeriod: {
        total: '3h20',
        cdg: '3h33',
        nce: '4h10',
        lys: '4h58',
      },

      percent1DayPairings: {
        total: '58%',
        cdg: '60%',
        nce: '54%',
        lys: '49%',
      },
      percent2DayPairings: {
        total: '40%',
        cdg: '20%',
        nce: '20%',
        lys: '20%',
      },
      percent3DayPairing: {
        total: '35%',
        cdg: '15%',
        nce: '20%',
        lys: '18%',
      },
    },
  },
  {
    id: 10,
    data: {
      realCosts: {
        total: '3 384 775',
        cdg: '1 765 224',
        nce: '942 308',
        lys: '677 243',
      },
      hotelRooms: {
        total: 709,
        cdg: 347,
        nce: 264,
        lys: 98,
      },
      offlineDeadHeads: {
        total: 191,
        cdg: 64,
        nce: 89,
        lys: 38,
      },
      aircraftChanges: {
        total: 46,
        cdg: 14,
        nce: 7,
        lys: 25,
      },
      splitDuties: {
        total: 30,
        cdg: 10,
        nce: 10,
        lys: 10,
      },
      blockPerDutyDay: {
        total: '4h55',
        cdg: '4h42',
        nce: '5h01',
        lys: '4h53',
      },
      blockPerDutyPeriod: {
        total: '2h20',
        cdg: '2h33',
        nce: '3h10',
        lys: '3h58',
      },
      percent1DayPairings: {
        total: '62%',
        cdg: '58%',
        nce: '67%',
        lys: '60%',
      },
      percent2DayPairings: {
        total: '60%',
        cdg: '30%',
        nce: '20%',
        lys: '10%',
      },
      percent3DayPairing: {
        total: '58%',
        cdg: '15%',
        nce: '50%',
        lys: '9%',
      },
    },
  },
  {
    id: 11,
    data: {
      realCosts: {
        total: '2 265 108',
        cdg: '1 000 099',
        nce: '862 974',
        lys: '321 007',
      },
      hotelRooms: {
        total: 201,
        cdg: 143,
        nce: 44,
        lys: 18,
      },
      offlineDeadHeads: {
        total: 154,
        cdg: 92,
        nce: 30,
        lys: 32,
      },
      aircraftChanges: {
        total: 6,
        cdg: 2,
        nce: 1,
        lys: 3,
      },
      splitDuties: {
        total: 60,
        cdg: 20,
        nce: 25,
        lys: 15,
      },
      blockPerDutyDay: {
        total: '4h31',
        cdg: '4h44',
        nce: '4h22',
        lys: '4h33',
      },
      blockPerDutyPeriod: {
        total: '5h20',
        cdg: '3h33',
        nce: '4h10',
        lys: '4h25',
      },
      percent1DayPairings: {
        total: '27%',
        cdg: '18%',
        nce: '29%',
        lys: '26%',
      },
      percent2DayPairings: {
        total: '30%',
        cdg: '25%',
        nce: '20%',
        lys: '18%',
      },
      percent3DayPairing: {
        total: '31%',
        cdg: '2%',
        nce: '70%',
        lys: '49%',
      },
    },
  },
  {
    id: 12,
    data: {
      realCosts: {
        total: '2 102 333',
        cdg: '942 308',
        nce: '770 118',
        lys: '942 308',
      },
      hotelRooms: {
        total: 189,
        cdg: 92,
        nce: 54,
        lys: 51,
      },
      offlineDeadHeads: {
        total: 72,
        cdg: 21,
        nce: 22,
        lys: 19,
      },
      aircraftChanges: {
        total: 7,
        cdg: 2,
        nce: 2,
        lys: 3,
      },
      splitDuties: {
        total: 51,
        cdg: 28,
        nce: 18,
        lys: 5,
      },
      blockPerDutyDay: {
        total: '4h22',
        cdg: '4h10',
        nce: '4h28',
        lys: '4h13',
      },
      blockPerDutyPeriod: {
        total: '5h30',
        cdg: '5h43',
        nce: '3h20',
        lys: '4h38',
      },
      percent1DayPairings: {
        total: '31%',
        cdg: '44%',
        nce: '17%',
        lys: '21%',
      },
      percent2DayPairings: {
        total: '18%',
        cdg: '28%',
        nce: '20%',
        lys: '15%',
      },
      percent3DayPairing: {
        total: '33%',
        cdg: '15%',
        nce: '55%',
        lys: '19%',
      },
    },
  },
];
