const dataHomeMock = {
  scenarioId: 1002,
  binId: 1,
  dataTypes: [
    {
      type: 'accommodation',
      source: 'import',
      count: 65,
      currentFile: {
        version: 2,
        binId: 1,
        binName: 'Default',
      },
      availableVersions: [1, 2],
      errorCount: null,
      newFilesAvailable: [
        {
          id: 2,
          version: 2,
          userDisplayName: 'Brandon Padilla',
          creationTime: '2019-11-11T10:15:53.630Z',
        },
      ],
    },
    {
      type: 'aircraftType',
      source: 'template',
      count: 3,
      currentFile: null,
      availableVersions: null,
      errorCount: 5,
      newFilesAvailable: [],
    },
    {
      type: 'commercialFlight',
      source: 'import',
      count: null,
      errorCount: null,
      currentFile: {
        version: 1,
        binId: 1,
        binName: 'Default',
      },
      availableVersions: [1, 2, 3, 4, 5],
      newFilesAvailable: [
        {
          id: 4,
          version: 2,
          userDisplayName: 'Brandon Padilla',
          creationTime: '2019-11-11T10:15:53.630Z',
        },
        {
          id: 5,
          version: 3,
          userDisplayName: 'Jonathan Sanchez',
          creationTime: '2019-09-05T13:10:53.630Z',
        },
        {
          id: 6,
          version: 4,
          userDisplayName: 'Alberto Chacón',
          creationTime: '2019-10-06T17:22:53.630Z',
        },
        {
          id: 7,
          version: 5,
          userDisplayName: 'Christian Portillo',
          creationTime: '2019-11-01T09:22:53.630Z',
        },
        {
          id: 15,
          version: 6,
          userDisplayName: 'David Morales',
          creationTime: '2019-10-31T11:45:53.630Z',
        },
      ],
    },
    {
      type: 'coterminalTransport',
      source: '',
      count: 4,
      currentFile: null,
      availableVersions: null,
      errorCount: null,
      newFilesAvailable: [],
    },
    {
      type: 'country',
      count: 248,
      currentFile: null,
      availableVersions: [1, 2, 3],
      errorCount: null,
      newFilesAvailable: [],
    },
    {
      type: 'base',
      count: 4,
      currentFile: null,
      availableVersions: null,
      errorCount: null,
      newFilesAvailable: [],
    },
    {
      type: 'currency',
      source: '',
      count: 157,
      currentFile: null,
      availableVersions: null,
      errorCount: null,
      newFilesAvailable: [],
    },
    {
      type: 'flight',
      source: 'import',
      count: 497,
      errorCount: null,
      currentFile: {
        version: 3,
        binId: 1,
        binName: 'Default',
      },
      availableVersions: [1, 2, 3, 4],
      newFilesAvailable: [],
    },
    {
      type: 'position',
      source: 'template',
      count: 4,
      currentFile: null,
      availableVersions: null,
      errorCount: null,
      newFilesAvailable: [],
    },
    {
      type: 'region',
      source: '',
      count: 5,
      currentFile: null,
      availableVersions: null,
      errorCount: null,
      newFilesAvailable: [],
    },
    {
      type: 'rule',
      source: 'template',
      count: null,
      currentFile: null,
      availableVersions: null,
      errorCount: null,
      newFilesAvailable: [],
    },
    {
      type: 'station',
      source: 'template',
      count: 111,
      currentFile: null,
      availableVersions: null,
      errorCount: null,
      newFilesAvailable: [],
    },
    {
      type: 'crewGroup',
      source: 'template',
      count: 8,
      currentFile: null,
      availableVersions: null,
      errorCount: null,
      newFilesAvailable: [],
    },
  ],
};

export default dataHomeMock;
