export const ganttConfiguration = {
  OPS: {
    indicatorBufferSize: '20',
    iconImage: {
      error: '0,0,50,50',
      warning: '100,0,50,50',
      caution: '200,0,50,50',
      info: '300,0,50,50',
    },
    paxConx: {
      MAYMISS: 'FFA500',
      MISS: 'C00000',
      OK: '009900',
      DEFAULT: '000000',
    },
    dayChangeLines: '2F4F4F',
    xViewMaxRange: '3',
    ruler: 'C71585',
    yViewMin: '0',
    departureDelayColor: 'FF0000',
    acUnserviceableWidth: '5',
    enableMultiScreen: 'true',
    minZoomInDays: '1',
    weekFirstDay: '1',
    forcedConnectionLineColor: 'FF0000',
    minZoomOffset: '1',
    gridLines: '778899',
    bufferRowCountPercentage: '30',
    enableTreeMode: 'true',
    timeBasedHoverColor: 'ff4d4d',
    treeInitialyCollapsed: 'true',
    horExtraFetch: '0.7',
    sierraPairings: {
      priority: ['OUT_BOTTOM_LEFT', 'OUT_TOP_LEFT', 'OUT_BOTTOM_RIGHT'],
      fillColor: [
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'transparent',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      OUT_TOP_LEFT: [
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '000000',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.departureStationCode + " "',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      borderWidth: [
        {
          condition: 'data.selectAll || data.selected',
          item: {
            hemColor: '',
            color: '',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 3,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 1,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      borderColor: [
        {
          condition:
            '(data.selectAll  || data.selected) && data.altType == "error"',
          item: {
            hemColor: '',
            color: 'D10000',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition:
            '(data.selectAll  || data.selected) && data.altType == "warning"',
          item: {
            hemColor: '',
            color: 'FF650C',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition:
            '(data.selectAll  || data.selected) && data.altType == "caution"',
          item: {
            hemColor: '',
            color: 'E8BB00',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition:
            '(data.selectAll  || data.selected) && data.altType == "info"',
          item: {
            hemColor: '',
            color: '5098E7',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: '(data.selectAll  || data.selected)',
          item: {
            hemColor: '',
            color: '000000',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      OUT_BOTTOM_RIGHT: [
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '000000',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: '" " + data.arrivalStationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      OUT_BOTTOM_LEFT: [
        {
          condition: 'data.altType == "error"',
          item: {
            hemColor: '',
            color: '',
            fontStyle: '',
            icon: 'error',
            override: false,
            text: ' ',
            width: 0,
            iconHeight: 21,
            iconWidth: 21,
            iconvOffset: -14,
            iconhOffset: -8,
            spotId: '',
          },
        },
        {
          condition: 'data.altType == "warning"',
          item: {
            hemColor: '',
            color: '',
            fontStyle: '',
            icon: 'warning',
            override: false,
            text: ' ',
            width: 0,
            iconHeight: 21,
            iconWidth: 21,
            iconvOffset: -14,
            iconhOffset: -8,
            spotId: '',
          },
        },
        {
          condition: 'data.altType == "caution"',
          item: {
            hemColor: '',
            color: '',
            fontStyle: '',
            icon: 'caution',
            override: false,
            text: ' ',
            width: 0,
            iconHeight: 21,
            iconWidth: 21,
            iconvOffset: -14,
            iconhOffset: -8,
            spotId: '',
          },
        },
        {
          condition: 'data.altType == "info"',
          item: {
            hemColor: '',
            color: '',
            fontStyle: '',
            icon: 'info',
            override: false,
            text: ' ',
            width: 0,
            iconHeight: 21,
            iconWidth: 21,
            iconvOffset: -14,
            iconhOffset: -8,
            spotId: '',
          },
        },
      ],
    },
    sierraFlights: {
      priority: [
        'TOP_LEFT',
        'BOTTOM_LEFT',
        'BOTTOM_CENTER',
        'OUT_TOP_LEFT',
        'OUT_BOTTOM_RIGHT',
      ],
      fillColor: [
        {
          condition: 'data.type === "CML"',
          item: {
            hemColor: '',
            color: '7600AE,0,350048,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'data.type === "DHI"',
          item: {
            hemColor: '',
            color: 'E339FF,0,9900E1,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'data.coverageSummary === "covered"',
          item: {
            hemColor: '',
            color: '5E77FF,0,0039CA,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'data.coverageSummary === "uncovered"',
          item: {
            hemColor: '',
            color: 'FF2B3A,0,AA1722,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'data.coverageSummary === "mixed"',
          item: {
            hemColor: '',
            color: 'FF8FAA,0,EB4C8F,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'data.coverageSummary === "undercovered"',
          item: {
            hemColor: '',
            color: 'FF9900,0,ED7722,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'data.coverageSummary === "overcovered"',
          item: {
            hemColor: '',
            color: 'E8BB00,0,D0A700,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '5E77FF,0,0039CA,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      OUT_TOP_LEFT: [
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '000000',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.departureStationCode + " "',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      borderWidth: [
        {
          condition: 'data.selectAll || data.selected',
          item: {
            hemColor: '',
            color: '',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 2,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 1,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      borderColor: [
        {
          condition: 'data.selectAll || data.selected',
          item: {
            hemColor: '',
            color: '000000',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      OUT_BOTTOM_RIGHT: [
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '000000',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: '" " + data.arrivalStationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      TOP_LEFT: [
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.flightNumber',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      BOTTOM_LEFT: [
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      BOTTOM_CENTER: [
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'fffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text:
              'formatDateTime(new Date(data.startDateTime), "HH:mm") + " - " + formatDateTime(new Date(data.endDateTime),"HH:mm")',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
    },
    BRF: {
      fillColor: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: 'CAE8C7,0,BDD4C1,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '67BE60,0,42834E,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      priority: ['TOP_LEFT', 'BOTTOM_LEFT'],
      TOP_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.stationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.stationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      BOTTOM_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
    },
    FLT: {
      fillColor: [
        {
          condition:
            'data.isLocked == true && data.coverageSummary === "covered"',
          item: {
            hemColor: '',
            color: 'C7CFFF,0,A6BAEC,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition:
            'data.isLocked == true && data.coverageSummary === "uncovered"',
          item: {
            hemColor: '',
            color: 'FFB5BA,0,E2AEB2,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition:
            'data.isLocked == true && data.coverageSummary === "mixed"',
          item: {
            hemColor: '',
            color: 'FFD8E1,0,F8C1D8,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition:
            'data.isLocked == true && data.coverageSummary === "overcovered"',
          item: {
            hemColor: '',
            color: 'F7E7A6,0,EFE1A6,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition:
            'data.isLocked == true && data.coverageSummary === "undercovered"',
          item: {
            hemColor: '',
            color: 'FFDBA6,0,F9CFB1,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'data.coverageSummary === "covered"',
          item: {
            hemColor: '',
            color: '5E77FF,0,0039CA,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: ' data.coverageSummary === "uncovered"',
          item: {
            hemColor: '',
            color: 'FF2B3A,0,AA1722,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'data.coverageSummary === "mixed"',
          item: {
            hemColor: '',
            color: 'FF8FAA,0,EB4C8F,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'data.coverageSummary === "overcovered"',
          item: {
            hemColor: '',
            color: 'E8BB00,0,D0A700,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'data.coverageSummary === "undercovered"',
          item: {
            hemColor: '',
            color: 'FF9900,0,ED7722,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: 'acd5f2,0,a7b6e2,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '139AE3,0,011DA2,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],

      priority: ['TOP_LEFT', 'BOTTOM_LEFT', 'BOTTOM_CENTER'],
      TOP_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '000000',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.flightNumber',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.flightNumber',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      BOTTOM_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '000000',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      BOTTOM_CENTER: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '000000',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text:
              'formatDateTime(new Date(data.startDateTime), "HH:mm") + " - " + formatDateTime(new Date(data.endDateTime),"HH:mm")',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'fffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text:
              'formatDateTime(new Date(data.startDateTime), "HH:mm") + " - " + formatDateTime(new Date(data.endDateTime),"HH:mm")',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
    },
    CNX: {
      fillColor: [
        {
          condition: 'data.isLocked == true && data.aircraftChange == true',
          item: {
            hemColor: '',
            color: 'D3D3D3,0,C7C7C7,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: 'E5E5E5,0,DBDBDB,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'data.aircraftChange == true',
          item: {
            hemColor: '',
            color: '828282,0,5E5E5E,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'B6B6B6,0,999999,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],

      priority: ['TOP_LEFT', 'BOTTOM_LEFT'],
      TOP_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.stationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.stationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      BOTTOM_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
    },
    CNX_AIRCRAFTCHANGE: {
      fillColor: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: 'D3D3D3,0,C7C7C7,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '828282,0,5E5E5E,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],

      priority: ['TOP_LEFT', 'BOTTOM_LEFT'],
      TOP_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.stationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.stationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      BOTTOM_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
    },
    LCNX: {
      fillColor: [
        {
          condition: 'data.isLocked == true && data.aircraftChange == true',
          item: {
            hemColor: '',
            color: 'D3D3D3,0,C7C7C7,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: 'E5E5E5,0,DBDBDB,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'data.aircraftChange == true',
          item: {
            hemColor: '',
            color: '828282,0,5E5E5E,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'B6B6B6,0,999999,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],

      priority: ['TOP_LEFT', 'BOTTOM_LEFT'],
      TOP_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.stationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.stationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      BOTTOM_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
    },
    LCNX_AIRCRAFTCHANGE: {
      fillColor: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: 'D3D3D3,0,C7C7C7,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '828282,0,5E5E5E,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],

      priority: ['TOP_LEFT', 'BOTTOM_LEFT'],
      TOP_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.stationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.stationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      BOTTOM_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
    },
    DBRF: {
      fillColor: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: 'CAE8C7,0,BDD4C1,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '67BE60,0,42834E,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      priority: ['TOP_LEFT', 'BOTTOM_LEFT'],
      TOP_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.stationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.stationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      BOTTOM_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
    },
    LO: {
      fillColor: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: 'F7F7F7,0,F1F1F1,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'E9E9E9,0,D7D7D7,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      borderWidth: [
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 1,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      borderColor: [
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'a0a0a0',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      priority: ['TOP_CENTER', 'BOTTOM_CENTER'],
      TOP_CENTER: [
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '000000',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.arrivalStationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      BOTTOM_CENTER: [
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '000000',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
    },
    DHI: {
      fillColor: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: 'F5BAFF,0,DBA6F5,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'E339FF,0,9900E1,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      priority: ['TOP_LEFT', 'BOTTOM_LEFT', 'BOTTOM_CENTER'],
      TOP_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.flightNumber',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.flightNumber',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      BOTTOM_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      BOTTOM_CENTER: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text:
              'formatDateTime(new Date(data.startDateTime), "HH:mm") + " - " + formatDateTime(new Date(data.endDateTime),"HH:mm")',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'fffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text:
              'formatDateTime(new Date(data.startDateTime), "HH:mm") + " - " + formatDateTime(new Date(data.endDateTime),"HH:mm")',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
    },
    CML: {
      fillColor: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: 'CFA6E3,0,B9A6BF,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: '7600AE,0,350048,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],

      priority: ['TOP_LEFT', 'BOTTOM_LEFT'],
      TOP_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.flightNumber',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.flightNumber',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      BOTTOM_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
    },
    COTRM: {
      fillColor: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: 'E6D9C6,0,D4C7B5,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'B7925B,0,83602B,100',
            fontStyle: '',
            icon: '',
            override: false,
            text: '',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],

      priority: ['TOP_LEFT', 'BOTTOM_LEFT'],
      TOP_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.stationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.stationCode',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
      BOTTOM_LEFT: [
        {
          condition: 'data.isLocked == true',
          item: {
            hemColor: '',
            color: '333333',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
        {
          condition: 'DEFAULT',
          item: {
            hemColor: '',
            color: 'ffffff',
            fontStyle: '12px Roboto',
            icon: '',
            override: false,
            text: 'data.duration',
            width: 0,
            iconHeight: 0,
            iconWidth: 0,
            spotId: '',
          },
        },
      ],
    },
    enabledepartureDelay: 'true',
    enableGroundTimeView: 'false',
    background1: 'ffffff',
    highlightedPeriod: '9ae6ff',
    lwBackground: 'e9c9db',
    actDepDelayLineColor: 'FF0000',
    maxZoomOutDays: '68',
    background2: 'd4d6d9',
    enableUnassignedPaneTreeMode: 'false',
    unservice: 'b41240',
    flightLegRequestMaxThreshold: '0',
    propagDepDelayLineColor: '000000',
    hangarIndicatorColor: '000000',
    enableArrDelayView: 'false',
    xaxisTimeBarBGColor: 'd5d9e2',
    verExtraFetch: '0.7',
    unsEqpCountToShow: '5',
    delayIndicator: 'DEP',
    initialPaneViewType: 'LegView',
    unserviceCompletion: '708090',
    xaxisTimeBarFontColor: '575f76',
    enableDoubleLineColour: 'false',
    tripGroundTimeView: 'false',
    retainMinZoomOffset: 'true',
    displayWeek: 'true',
    estDepDelayLineColor: '000000',
    yViewMax: '6',
  },
};

export const ganttPanes = {
  OPS: {
    PairingPane: 'true',
    FlightPane: 'false',
    EmptyPane: 'false',
  },
};

export const ganttPopupConfiguration = {
  OPS: {
    sierraPairings:
      'data.carrierCode+" "+data.flightNumber+" "+( data.flightSuffix ? data.flightSuffix : \'\' )+" ( "+data.carrierCodeATC+")"+"<br/>"    +data.departureAirport+" -> "+data.arrivalAirport+"<br/>"    +(formatDateTime(getUTCDateForTimeInMilliseconds(data.flightGanttDTO.flightToolTipDTO.std),getDefaultTimeFormat()))    +"/"+ formatDateTime(getUTCDateForTimeInMilliseconds(data.flightGanttDTO.flightToolTipDTO.bestStartTimePropag),getDefaultTimeFormat())+" "+data.flightStatus+"<br/>"    +((data.flightGanttDTO.flightToolTipDTO.sta!=undefined) ? (formatDateTime(getUTCDateForTimeInMilliseconds(data.flightGanttDTO.flightToolTipDTO.sta),getDefaultTimeFormat())) : \'\')+"/"    +  formatDateTime(getUTCDateForTimeInMilliseconds(data.flightGanttDTO.flightToolTipDTO.bestEndTimePropag),getDefaultTimeFormat())+" "+data.fltTime             +((data.flightInOperationDTO.nextInformationDateTime!=undefined) ? (" <br/>" + "NI:"     +formatDateTime(getUTCDateForTimeInMilliseconds(data.flightInOperationDTO.nextInformationDateTime))) : \'\')     +((data.notificationdisplay!=undefined) ? (" <br/>"+data.notificationdisplay) : \'\')    ',
  },
};
