export const GENERAL = {
  NOTIFICATION_INCREMENT: 'NOTIFICATION_INCREMENT',
  NOTIFICATION_RESET: 'NOTIFICATION_RESET',
  NOTIFICATION_UNREGISTER: 'NOTIFICATION_UNREGISTER',
  NOTIFICATION_FETCHING: 'NOTIFICATION_FETCHING',
  NOTIFICATION_SUCCESS: 'NOTIFICATION_SUCCESS',
  NOTIFICATION_ERROR: 'NOTIFICATION_ERROR',
  NOTIFICATION_ADD: 'NOTIFICATION_ADD',
  NOTIFICATION_PAGE_SIZE: 30,
  NOTIFICATION_SINGLE_DELETE: 'NOTIFICATION_SINGLE_DELTE',
  NOTIFICATION_ALL_DELETE: 'NOTIFICATION_ALL_DELETE',
  NOTIFICATION_ALL_SEEN: 'NOTIFICATION_ALL_SEEN',
  VIEWED_ALL_NOTIFICATION: 'VIEWED_ALL_NOTIFICATION',
  NOTIFICATION_CLEANUP: 'NOTIFICATION_CLEANUP',
  NOTIFICATION_BAR_CLOSE: 'NOTIFICATION_BAR_CLOSE',
  SET_CURRENT_NAV_MENU: 'SET_CURRENT_NAV_MENU',
};

export const SCENARIOS = {
  SET_OPEN_SCENARIO: 'SET_OPEN_SCENARIO',
  SET_READONLY_SCENARIO: 'SET_READONLY_SCENARIO',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
};

export const SOLVER = {
  PUSH_LATEST_JOB_STATUS: 'PUSH_LATEST_JOB_STATUS',
  TRIGGER_SHOW_ERRORS: 'TRIGGER_SHOW_ERRORS',
};

export const USER = {
  SET_USER_DATA: 'SET_USER_DATA',
  USER_DATA_CLEAN_UP: 'USER_DATA_CLEAN_UP',
  SET_PERMISSION: 'SET_PERMISSION',
};

export const READ_ONLY = 'ReadOnly';

export const DATA = {
  SET_MASTER_DATA: 'SET_MASTER_DATA',
  CLEAR_MASTER_DATA: 'CLEAR_MASTER_DATA',
};

export const PAIRING = {
  SET_TIMELINE_KEYLIST: 'SET_TIMELINE_KEYLIST',
  DELETE_TIMELINE_KEYLIST: 'DELETE_TIMELINE_KEYLIST',
  UPDATE_TIMELINE_KEYS: 'UPDATE_TIMELINE_KEYS',
  REMOVE_TIMELINE_KEYS: 'REMOVE_TIMELINE_KEYS',
  SET_ALL_TIMELINE_KEYLIST: 'SET_ALL_TIMELINE_KEYLIST',
  REMOVE_KEYS: 'REMOVE_KEYS',
  CHANGE_LEGS_TO_DEADHEADS: 'CHANGE_LEGS_TO_DEADHEADS',
  CHANGE_DEADHEADS_TO_LEGS: 'CHANGE_DEADHEADS_TO_LEGS',
  RESET_TIMELINE_KEYS: 'RESET_TIMELINE_KEYS',
  BULK_UPDATE_TIMELINE_KEYS: 'BULK_UPDATE_TIMELINE_KEYS',
};
