const messages = 'SOLVER.statusMessages';

const solverStatus = [
  {
    statusId: 1,
    status: 'READY_TO_LAUNCH',
    textBar: `${messages}.ready.textBar`,
    label: `${messages}.ready.label`,
    icon: 'rocket',
    activeBtns: ['play'],
    routes: [2],
    showTimer: false,
    showLabel: false,
    dateCurrent: false,
    timerType: '',
    block: false,
  },
  {
    statusId: 2,
    status: 'Creating',
    textBar: `${messages}.Creating.textBar`,
    label: `${messages}.Creating.label`,
    icon: 'slow_motion_video',
    activeBtns: ['stop'],
    routes: [3, 4],
    showTimer: false,
    showLabel: true,
    dateCurrent: true,
    timerType: 'keep',
    block: true,
  },
  {
    statusId: 3,
    status: 'Running',
    textBar: `${messages}.Running.textBar`,
    label: `${messages}.Running.label`,
    icon: 'running_icon',
    activeBtns: ['stop'],
    routes: [4, 8, 9],
    showTimer: true,
    showLabel: true,
    dateCurrent: true,
    timerType: 'keep',
    block: true,
  },
  {
    statusId: 4,
    status: 'Done-success',
    textBar: `${messages}.Done-success.textBar`,
    label: `${messages}.Done-success.label`,
    icon: 'complete_icon',
    activeBtns: ['preview', 'endorse', 'more'],
    routes: [8],
    showTimer: true,
    showLabel: true,
    dateCurrent: true,
    timerType: 'elapsed',
    block: true,
  },
  {
    statusId: 5,
    status: 'Done-stopped',
    textBar: `${messages}.Done-stopped.textBar`,
    label: `${messages}.Done-stopped.label`,
    icon: 'failed_icon',
    activeBtns: ['play'],
    routes: [8],
    showTimer: true,
    showLabel: true,
    dateCurrent: true,
    timerType: 'elapsed',
    block: true,
  },
  {
    statusId: 6,
    status: 'Done-failed',
    textBar: `${messages}.Done-failed.textBar`,
    label: `${messages}.Done-failed.label`,
    icon: 'failed_icon',
    activeBtns: ['play'],
    routes: [8],
    showTimer: true,
    showLabel: true,
    dateCurrent: true,
    timerType: 'elapsed',
    block: true,
  },
  {
    statusId: 7,
    status: 'Waiting',
    textBar: `${messages}.Waiting.textBar`,
    label: `${messages}.Waiting.label`,
    icon: 'slow_motion_video',
    activeBtns: ['stop'],
    routes: [1, 2],
    showTimer: false,
    showLabel: true,
    dateCurrent: true,
    timerType: 'elapsed',
    block: false,
  },
  {
    statusId: 8,
    status: 'Sending',
    textBar: `${messages}.Sending.textBar`,
    label: `${messages}.Sending.label`,
    icon: 'slow_motion_video',
    activeBtns: ['stop'],
    routes: [1, 2],
    showTimer: false,
    showLabel: true,
    dateCurrent: true,
    timerType: 'elapsed',
    block: false,
  },
  {
    statusId: 9,
    status: 'Fetching',
    textBar: `${messages}.Fetching.textBar`,
    label: `${messages}.Fetching.label`,
    icon: 'running_icon',
    activeBtns: ['stop'],
    routes: [1, 2],
    showTimer: true,
    showLabel: true,
    dateCurrent: true,
    timerType: 'elapsed',
    block: false,
  },
  {
    statusId: 10,
    status: 'Launching',
    textBar: `${messages}.Launching.textBar`,
    label: `${messages}.Launching.label`,
    icon: 'slow_motion_video',
    activeBtns: [],
    routes: [3, 4],
    showTimer: false,
    showLabel: true,
    dateCurrent: false,
    timerType: 'keep',
    block: true,
  },
  {
    statusId: 11,
    status: 'Stopping',
    textBar: `${messages}.Stopping.textBar`,
    label: `${messages}.Stopping.label`,
    icon: 'failed_icon',
    activeBtns: [],
    routes: [8],
    showTimer: false,
    showLabel: true,
    dateCurrent: false,
    timerType: 'elapsed',
    block: true,
  },
];

export function getStatusObject(name, previousStatus = 'READY_TO_LAUNCH') {
  const status = solverStatus.filter(status => status.status === name);
  return status.length
    ? status[0]
    : solverStatus.filter(status => status.status === previousStatus)[0];
}
