export const user = {
  userData: {
    email: 'admin@kronos.com',
    firstName: 'admin',
    lastName: 'admin',
    username: 'admin',
    id: '2',
    role: 'Administrator',
  },
  permissions: [
    'scenario_rule_edit',
    'template_add',
    'tm_v',
    'widget_configure',
    'settings_configure',
    'reports_generate',
    'template_edit',
    'dashboard_manage',
    'scenario_manage',
    'bin_view',
    'scenario_edit',
    'solver_evaluate',
    'scenario_rule_view',
    'scenario_add',
    'scenario_data_manage',
    'scenario_data_view',
    'users_view',
    'user_role_view',
    'notification_view',
    'template_rule_view',
    'user_role_manage',
    'widget_view',
    'pairing_manage',
    'dashboard_view',
    'scenario_publish',
    'reports_manage',
    'pairing_view',
    'pairing_edit',
    'settings_edit',
    'widget_edit',
    'template_ruleset_manage',
    'template_data_view',
    'template_rule_edit',
    'template_manage',
    'solver_view',
    'scenario_ruleset_view',
    'uma_protection',
    'solver_manage',
    'template_data_manage',
    'audit_view',
    'import_view',
    'notification_manage',
    'sc_v',
    'bin_manage',
    'scenario_delete',
    'import_action',
    'template_ruleset_view',
    'users_manage',
    'template_delete',
    'scenario_ruleset_manage',
  ],
};
